name: Manual Trigger Workflow with username
#get username information
on:
  push:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Purpose of deployment'
        default: ''
        required: true
        type: string

jobs:
  print-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo Print projectt

  print-username:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Print username
        run: |
          echo "The username selected option: ${{inputs.choice }}"
