name: Manual Trigger Workflow with username
#get username information
on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Purpose of deployment'
        default: ''
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print username
        run: |
          echo "The username selected option: ${{inputs.choice }}"
