name: Manual Trigger Workflow with username
#get username information
on:
  push:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Deploy to Production?'
        default: ''
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest
    if: ${{ inputs.choice }} == "yes"
    steps:
      - name: Print the username
        run: |
          echo "The username selected option: ${{ inputs.choice }}"
